# Generated by Django 4.0.2 on 2022-03-08 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('inq_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=12)),
                ('wmobile', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=40)),
                ('dob', models.DateField(blank=True, default=datetime.date(2022, 1, 1), help_text='write proper date', null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True)),
                ('isPassport', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=50)),
                ('address', models.TextField(default='some address', max_length=300)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('pincode', models.CharField(default='', max_length=100)),
                ('instaid', models.CharField(default='', max_length=100)),
                ('fbid', models.CharField(default='', max_length=100)),
                ('marital_status', models.CharField(default='', max_length=100)),
                ('no_child', models.CharField(default='', max_length=100)),
                ('fdate1', models.DateField(blank=True, default=datetime.date(2022, 1, 1), help_text='write proper date', null=True)),
                ('tdate1', models.DateField(blank=True, default=datetime.date(2022, 1, 1), help_text='write proper date', null=True)),
                ('qual1', models.CharField(default='', max_length=100)),
                ('ctype1', models.CharField(default='', max_length=100)),
                ('marks1', models.CharField(default='', max_length=100, null=True)),
                ('school1', models.CharField(default='', max_length=100)),
                ('fdate2', models.DateField(blank=True, default=datetime.date(2022, 1, 1), help_text='write proper date', null=True)),
                ('tdate2', models.DateField(blank=True, default=datetime.date(2022, 1, 1), help_text='write proper date', null=True)),
                ('qual2', models.CharField(default='', max_length=100)),
                ('ctype2', models.CharField(default='', max_length=100)),
                ('marks2', models.CharField(default='', max_length=100)),
                ('school2', models.CharField(default='', max_length=100)),
                ('fdate3', models.DateField(blank=True, default=datetime.date(2022, 1, 1), help_text='write proper date', null=True)),
                ('tdate3', models.DateField(blank=True, default=datetime.date(2022, 1, 1), help_text='write proper date', null=True)),
                ('qual3', models.CharField(default='', max_length=100)),
                ('ctype3', models.CharField(default='', max_length=100)),
                ('marks3', models.CharField(default='', max_length=100)),
                ('school3', models.CharField(default='', max_length=100)),
                ('fdate4', models.DateField(blank=True, default=datetime.date(2022, 1, 1), help_text='write proper date', null=True)),
                ('tdate4', models.DateField(blank=True, default=datetime.date(2022, 1, 1), help_text='write proper date', null=True)),
                ('qual4', models.CharField(default='', max_length=100)),
                ('ctype4', models.CharField(default='', max_length=100)),
                ('marks4', models.CharField(default='', max_length=100)),
                ('school4', models.CharField(default='', max_length=100)),
                ('fdate5', models.DateField(blank=True, default=datetime.date(2022, 1, 1), help_text='write proper date', null=True)),
                ('tdate5', models.DateField(blank=True, default=datetime.date(2022, 1, 1), help_text='write proper date', null=True)),
                ('org1', models.CharField(default='', max_length=100)),
                ('role1', models.CharField(default='', max_length=100)),
                ('fdate6', models.DateField(blank=True, default=datetime.date(2022, 1, 1), help_text='write proper date', null=True)),
                ('tdate6', models.DateField(blank=True, default=datetime.date(2022, 1, 1), help_text='write proper date', null=True)),
                ('org2', models.CharField(default='', max_length=100)),
                ('role2', models.CharField(default='', max_length=100)),
                ('fname', models.CharField(default='', max_length=100)),
                ('occupation_type', models.CharField(default='', max_length=100)),
                ('occupation_name', models.CharField(default='', max_length=100)),
                ('english_test', models.CharField(blank=True, choices=[('IELTS-General/Academy', 'IELTS-General/Academy'), ('TOEFL', 'TOEFL'), ('PTE', 'PTE')], max_length=100, null=True)),
                ('english_test_date', models.DateField(blank=True, default=datetime.date(2022, 1, 1), help_text='write proper date', null=True)),
                ('lband', models.IntegerField(blank=True, default=0)),
                ('rband', models.IntegerField(blank=True, default=0)),
                ('wband', models.IntegerField(blank=True, default=0)),
                ('sband', models.IntegerField(blank=True, default=0)),
                ('oband', models.IntegerField(blank=True, default=0)),
                ('General_test_date', models.DateField(blank=True, default=datetime.date(2022, 1, 1), help_text='write proper date', null=True)),
                ('General_test_score', models.IntegerField(default=0, null=True)),
                ('rejected', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100)),
                ('rejectedcountry', models.CharField(default='', max_length=100)),
                ('ref', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
