# Generated by Django 4.0.2 on 2022-03-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radientapp', '0002_smallinq'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
